### ISSUE TITLE
使用curl无法上传文件

### ISSUE THREAD

**Issue by linersheng** [hetianyi/godfs#10]
curl -v -F "file=@/home/xxxx/tmpfiles/test.bin" "http://192.168.2.58:1024/upload/"
* Hostname was NOT found in DNS cache
*   Trying 192.168.2.58...
* Connected to 192.168.2.58 (192.168.2.58) port 1024 (#0)
> POST /upload/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 192.168.2.58:1024
> Accept: */*
> Content-Length: 1048776
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------ae65b7cb65f4f67e
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

**Comment by hetianyi** [comment]
curl请使用http端口8001，
1024一般是tcp端口。
