### ISSUE TITLE
docker部署api获取

### ISSUE THREAD

**Issue by 93Alliance** [hetianyi/godfs#11]
**docker** 部署之后:

1. tracker容器是-p 1022:1022
2. storage容器是 -p 1024:1024 -p 80:8001

目前我是在单机，而且只有一个 **stroage**,为什么每次我上传是通过 stroage上传，下载也是通过 stroage 下载，那么 **tracker** 有什么作用？

只是做多个 stroage 之间的同步么？

如果是多个 storage 那么我该如何确定到底访问哪一个去上传/下载资源？

**Comment by hetianyi** [comment]
tracker的作用并不是网关，而是协调文件的组内同步和文件查询，上传下载都是直接和storage交互，如果不想直接和storage交互，可以使用nginx作为统一网关，与tracker和storage进行通讯。
多个storage：
group相同的实例会相互进行文件同步，直至最终达成一致状态。
可以在上传的时候指定group来确定文件上传到哪一个组，如果一个组有多个storage实例，则随机选择一个进行上传下载。
每个storage均可以进行下载，但是可以通过参数```upload_enable```则能够控制是否能够上传。
可以参考代码中的[集群示例](https://github.com/hetianyi/godfs/tree/master/example)来进行网关的自动化配置，docker镜像为：[hehety/nginx:godfs](https://cloud.docker.com/repository/docker/hehety/nginx/tags)，通过此网关则无需关心去哪个实例去下载上传。
