### ISSUE TITLE
是否能关闭tracker？

### ISSUE THREAD

**Issue by 93Alliance** [hetianyi/godfs#13]
我是否能够关闭 tracker ，单独运行 storage，但是这样storage内会报错？

**Comment by hetianyi** [comment]
可以，指定```trackers=""```即可，这时storage会以standalone模式运行

**Comment by 93Alliance** [comment]
ok，storage 可以通过http delete么？或者tcp？

**Comment by hetianyi** [comment]
delete目前不支持，将来会考虑加上此功能！

**Comment by 93Alliance** [comment]
好的，谢了
