### ISSUE TITLE
请问godfs支持访问控制么，比如token机制

### ISSUE THREAD

**Issue by Wizzercn** [hetianyi/godfs#14]
需求，上传的文件可以在系统内打开，系统外不能打开或者可以设置有效期

**Comment by hetianyi** [comment]
godfs保存管理文件，但是没有访问权限控制机制，需要前端具体的应用系统来做控制。
因为每家的应用系统的权限控制方式均有不同，所以不可能做到这一步，除非根据业务做个性化定制。
有效期可以通过定制来实现（比如为文件创建临时别名并设置有效期），但是为了避免给系统数据库带来不必要的开销，因此不予实现，可考虑在前端系统实现。
另：你所说的系统内打开具体是控制在什么范围内不清楚，但是godfs支持简单的防盗链机制。

**Comment by Wizzercn** [comment]
请问下，防盗链机制具体怎么使用

**Comment by Wizzercn** [comment]
能否提供fastdfs那样的token防盗链机制？fastdfs服务可以自己判断token是否有效，而不是单单配个allowed_domain而已，文件的url应该是可以分享出去的。

**Comment by hetianyi** [comment]
感谢反馈，下一个版本将提供token机制！

**Comment by hetianyi** [comment]
https://github.com/hetianyi/godfs/blob/master/README_zh.md#token%E7%9A%84%E4%BD%BF%E7%94%A8
