### ISSUE TITLE
[base_dao.go:58] error prepare db file: open source file failed

### ISSUE THREAD

**Issue by myrust-go** [hetianyi/godfs#18]
no db file。

安装一切都成功了，可是提示没有db file。

[root@localhost godfs]# /usr/local/godfs/bin/tracker -c /usr/local/godfs/conf/tracker.conf
INFO  - 2019-10-21 19:31:06,340 [tracker.go:32] using config file: /usr/local/godfs/conf/tracker.conf
INFO  - 2019-10-21 19:31:06,341 [base_dao.go:54] no db file found, init db file from template.

**Comment by myrust-go** [comment]
fInfo, e := os.Stat(app.BasePath + "/data/storage.db")

感觉这句代码写的有问题哟

**Comment by kaiwenli** [comment]
晚一点，等孩子睡了提交一个fix

**Comment by hetianyi** [comment]
tracker.conf的配置base_path没有修改，改为/usr/local/godfs即可
