### ISSUE TITLE
最近想学分布式文件系统相关知识, 想向作者请假一下该怎么学习？需要哪些储备知识?

### ISSUE THREAD

**Issue by tony-is-coding** [hetianyi/godfs#20]
目前学过一段时间的go了, 然后对dfs 类系统兴趣较大，请问应该怎么入手学习? 以及如何开始一个 分布式系统的设计与开发?

**Comment by hetianyi** [comment]
学习分布式系统或者需要自行搭建的可以看下这个项目：
https://github.com/minio/minio
有组织长期维护，上手比较简单，功能也很强大
