### ISSUE TITLE
docker 在这有什么用

### ISSUE THREAD

**Issue by wwj007176** [hetianyi/godfs#3]
我使用docker 安装完, 容器启动 ,可以使用curl 来上传文件
但是怎么下载文件呢？？
还是要在容器外在完整的安装一遍？？

**Comment by hetianyi** [comment]
可以使用http下载，例如wget或者浏览器，形如：
```http://host:port/download/G01/110/S/4168e9deff1d0e80b6d69b74d4fac7c0/134.jpg```
或者自行编译一个客户端（参考文档，windows、Linux均可），
通过命令行下载文件：
``` client -d G01/110/S/4168e9deff1d0e80b6d69b74d4fac7c0 -n 123.jpg ```
