### ISSUE TITLE
为什么用sqlite而不用其它性能更好的K/V存储库？

### ISSUE THREAD

**Issue by yatniel7** [hetianyi/godfs#4]
RT

**Comment by hetianyi** [comment]
目前只考虑将数据结构化存储，kv不太方便做稍微复杂的查询和数据关系绑定，sqlite性能还不错，上传500w条测试数据用了不到两天。另外，你觉得哪些kv数据库更好呢？可以推荐下

**Comment by yatniel7** [comment]
rocksdb, leveldb, boltdb, buntdb, 都是不错的K/V库，速度快，依赖小。

SQLITE量大了之后性能就不是那么理想了。

**Comment by hetianyi** [comment]
目前来看，sqlite是最简单的实现方式，支持千万级数据量还是不成问题的，如果有更多的数据量就需要考虑架构和文件分组了，使用sqlite我只需要引入sqlite3的驱动即可，对于数据迁移也是很简单的。你说的这些kv数据库集成进来需要自己编译安装配置，还有需要集成数据库相应的客户端之类的问题，相对而言，作为IO密集型的服务中，数据库的性能并不是那么重要。

**Comment by yatniel7** [comment]
boltdb, buntdb 这些K/V，是纯GO实现，没有额外的安装配置，比集成sqlite3驱动要简单。
当然，文件实在太多， 部署多组服务器也是OK的。

纯建议。另外问一下，性能测试怎么样了？

**Comment by sjqzhang** [comment]
可以考虑用leveldb
Go-fastdfs就是用这个，性能扛扛的。
