### ISSUE TITLE
建议要能可以mount

### ISSUE THREAD

**Issue by ppabc** [hetianyi/godfs#6]
要能可以mount就好了，就像普通磁盘可以挂载，可以取消，数据能自动同步，分布式

**Comment by hetianyi** [comment]
“数据能自动同步，分布式”功能已有，mount......不太理解

**Comment by ppabc** [comment]
可以mount，就像普通磁盘可以挂载，可以SSH服务器上操作文件的增删改查，批量查文件删除文件

**Comment by hetianyi** [comment]
godfs不是底层的文件系统而是一个应用，不能直接挂载/卸载
