### ISSUE TITLE
请问secret=OASAD834jA97AAQE761==是如何生成的？

### ISSUE THREAD

**Issue by rubyhan1314** [hetianyi/godfs#7]
你好，我安装并启动服务后，在上传文件的时候，无法通过校验。所以想请问一下secret=OASAD834jA97AAQE761==是如何生成的？是secret的原因吗？期盼回复，非常感谢！
下面是报错信息：
![wx20190214-171056](https://user-images.githubusercontent.com/40972628/52775854-94f97d80-307b-11e9-98d7-f5ccaeb98b3a.png)

**Comment by hetianyi** [comment]
请执行命令：
```client config ls```
查看一下配置文件的secret是什么，如果出现bad secret，可能是server和client的secret不匹配导致，请仔细检查一下启动server的secret是否修改过。
client端设置secret通过：```client config set secret="xxx"```，
server端可通过修改配置文件中的secret或者通过环境变量覆盖。
另外：```secret=OASAD834jA97AAQE761==```只是最开始开发时随手写的。
如仍有问题，可在此贴一下各个服务的启动命令。

**Comment by linersheng** [comment]
执行就可以了
/usr/local/godfs/bin/client config set secret=OASAD834jA97AAQE761==

**Comment by rubyhan1314** [comment]
在客户端设置secret的值就可以了，已经解决，非常感谢。。
