### ISSUE TITLE
godfs运行后，不能上传文件

### ISSUE THREAD

**Issue by SmarterEric** [hetianyi/godfs#9]
![181550138980_ pic_hd](https://user-images.githubusercontent.com/38749449/52780192-a004db80-3084-11e9-962c-f78f3633a984.jpg)
![171550138729_ pic_hd](https://user-images.githubusercontent.com/38749449/52780194-a2673580-3084-11e9-8c71-882a246705db.jpg)
![161550138693_ pic_hd](https://user-images.githubusercontent.com/38749449/52780199-a5622600-3084-11e9-9184-a76187b8a5ad.jpg)

**Comment by linersheng** [comment]
在Ubuntu server 16.04上也遇到类型的问题

**Comment by linersheng** [comment]
执行就可以了
/usr/local/godfs/bin/client config set secret=OASAD834jA97AAQE761==

**Comment by hetianyi** [comment]
see https://github.com/hetianyi/godfs/issues/7#issuecomment-463577966
